# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/omvjro"

[social.params]
icon = "brand-github"

[[social]]
identifier = "wiki"
name = "DOL wiki"
url = "https://degreesoflewditycn.miraheze.org/wiki/Special:用户贡献/+++嫉妒"

[social.params]
icon = "brand-wikipedia"

[[social]]
identifier = "para"
name = "ParaTranz"
url = "https://paratranz.cn/users/44232"

[social.params]
icon = "square-rounded-letter-p"
